version: '3'

services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./docker/nginx
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_LOG_PATH}:/var/log/nginx
            - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - internal

    php-fpm:
        container_name: php-fpm
        restart: always
        build: 
            context: ./docker/php-fpm
            args:
                INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
                INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
                INSTALL_GD=${PHP_FPM_INSTALL_GD}
                INSTALL_GD=${PHP_FPM_INSTALL_GD}
                INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
                INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
                INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
                INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
                INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
                INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
                INSTALL_NODE=${PHP_FPM_INSTALL_NODE}
        
        expose: 
            - "9000:9000"
        volumes:
            - ${APPLICATION}:/var/www/html:cached
        networks:
            - internal

    mysql:
        container_name: mysql
        restart: always
        build:
            context: ./docker/mysql
        ports: 
            - "${MYSQL_PORT}:3306"
            volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        enviroments:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - internal

    redis:
        image: sickp/alpine-redis:3.2.2
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - internal

networks:
    internal:
        driver: bridge